### ISSUE TITLE
Ability to invite someone/share the event

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#52] opened 2020-05-31 13:56 UTC
Could we queue this as a v2 development?

**Comment by GeorgeBellTMH** [comment] 2020-05-31 14:51
This should create an email or text and be sent via amplify/expo notification api.

**Comment by GeorgeBellTMH** [comment] 2020-07-17 03:55
Duplicate of #207

**Closed by GeorgeBellTMH** 2020-07-17 03:55 UTC
Labels: V2
