### ISSUE TITLE
beta site not loading

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#206] opened 2020-06-17 20:16 UTC
An interested thing happened today.

Zulema attempted to get on to beta.jesuscollective.com on Firefox on PC and it never loaded (it stayed as a blank page). Then she tried on Chrome and had no issues.

However, at the same time, Matt tried on Chrome and had the same issue she had on Firefox. He is also on a PC. 

Both Chrome and Firefox are up to date for both of them.

**Comment by JonEsparaz** [comment] 2020-06-18 05:40
I saw a couple auth-related errors in Sentry that match the time and OS/browser... Could be the cause, but can’t be 100% sure.

**Comment by GeorgeBellTMH** [comment] 2020-06-23 07:14
Closing this, doesn't seem to have reoccurred....

**Closed by GeorgeBellTMH** 2020-06-23 07:14 UTC
Labels: Priority 1, bug
