### ISSUE TITLE
Change dynamo dropdowns to query after 3 character instead of 4

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1174] opened 2022-03-23 15:13 UTC
Case in point - If you type "Jon" when trying to add "Jon Hand" to paid users in a course, "Jon Hand" doesn't appear as an option. If you type "Hand" he does. Maybe the dropdown is not returning every profile option or it is but the box is not scrollable?

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=866467137)

**Comment by GeorgeBellTMH** [comment] 2022-07-26 03:03
This is by design....search only works after 4 letters...we can modify the search to do less...

**Comment by GeorgeBellTMH** [comment] 2022-07-26 03:05
I think this was done by Amplify team to save money a bit (by default) on amplify side...we changed it on TMH Web...so it should be doable...

**Comment by itbel** [comment] 2022-08-23 20:01
Closing as this was implemented in #1221

**Closed by itbel** 2022-08-23 20:01 UTC
