### ISSUE TITLE
Assignment input field overlapping other elements

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#778] opened 2021-03-08 17:20 UTC
The "write your assignment" text box appears overlaying other parts of the assignment page. This occurs in both the assignment and response lesson types. 

<img width="1436" alt="Screen Shot 2021-03-08 at 10 08 23 AM" src="https://user-images.githubusercontent.com/48295718/110356758-943c3700-8008-11eb-9bad-9fd871b2e078.png">

<img width="1440" alt="Screen Shot 2021-03-08 at 10 07 49 AM" src="https://user-images.githubusercontent.com/48295718/110356753-92727380-8008-11eb-865f-e7b4a1e831b1.png">

**Comment by GeorgeBellTMH** [comment] 2021-03-08 21:18
Duplicate of #783

**Comment by GeorgeBellTMH** [comment] 2021-03-11 06:31
Let us know if this is fixed as well...

**Closed by GeorgeBellTMH** 2021-03-11 06:31 UTC
Labels: Courses, Design, High Priority
