### ISSUE TITLE
Groups: Invite

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#208] opened 2020-06-17 21:33 UTC
We need to create the ability for someone to invite someone else to join a group. This would be a button in the group that would trigger something like a "enter person's name" and the ability to send them an email invite to the group. This will come into play for all 3 group categories:

- Public, open (anyone can invite anyone to the group)
- Public, closed (only group admins can invite someone, but everyone has the ability to "request to join"
- Private (only group admins can invite someone to the group) - JC admins can see all private groups

**Comment by GeorgeBellTMH** [comment] 2020-07-17 03:56
Duplicate of #207

**Closed by GeorgeBellTMH** 2020-07-17 03:56 UTC
Labels: V2
