### ISSUE TITLE
About me window too small on edit profile page

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#331] opened 2020-07-14 14:14 UTC
The about me text bar in the edit profile page is very small.  Most people will write quite a bit here (and we want them to) which makes it hard to track what you're typing in such a small bar. Can we enlarge the field space so you can see more of what you've typed?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucastbelem** [comment] 2020-07-14 17:48
Duplicate of #310

**Comment by mmacedom** [comment] 2020-07-20 01:31
@lucastbelem @MattMilesJC I have increased the height of the "About Me" container so it accommodates around 530 characters (around 5 lines of copy) without triggering any scrolling behaviour on desktop . Please advise if there is a need to add more vertical space to it. Thanks

**Closed** 2020-07-20 01:35 UTC
