### ISSUE TITLE
All group types should have a green box instead of leave/unfollow etc.

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#334] opened 2020-07-14 14:24 UTC
**Describe the bug**
The button says 'leave' on resources (and I think also on groups) once you've joined/follow that resource.  The button should be something that confirms you are joined (group) or following/tracking (resources).  Similar to the 'don't attend' issue for events.

**Comment by GeorgeBellTMH** [comment] 2020-07-14 16:56
Duplicate of #329

**Comment by GeorgeBellTMH** [comment] 2020-07-14 17:02
We need to figure out the best way to do this that works the same for events/resources/courses/groups/orgs...there are a few different cases that need to be handled:

1) You are the owner of the group - in this case there are no actions that you can take (owners are already members, and can't leave except by deleting the group) - so it should say something along the lines of "You Own This Group"

2) This part is solved - if you are not a member or owner, you should be able to join the group
      a) on the homescreen
      b) on the group screen itself

3) If you are a member, we need to give the user a way to not be a member - because being a member results in you getting alerts and emails....if people can't leave, they can't opt out of alerts
    a) They should be able to leave when they are in the home screen
    b) I believe they should be able to leave when they are in the group detail screen

Problem is that green dot doesn't let user know they can leave, and the "leave" text doesn't let them know they are actually a member...

I think we need some indicator that they are a member, but also that if they click they can leave...

**Comment by GeorgeBellTMH** [comment] 2020-07-14 17:03
Additionally there will eventually be groups that you can't join (but you must still be able to leave) - for example invite only groups, or groups where you need to ask to join.

**Comment by lucastbelem** [comment] 2020-07-14 17:42
@GeorgeBellTMH thanks for laying this out. Here are some thoughts re your points:

1 and 2: Perfect! That's exactly how it should go.
3: You should definitely be able to leave a group/resource/event. However, Matt doesn't want that to be as easy as showing up on the homescreen. So, all of that to say, "a" should not be a thing. "b" should be the only way someone can leave group/resource/event. 

On the homescreen, the user should just see text/graphic showing they're members or are attending, etc.

Let me know if there are more questions on this. 

P.s. @MattMilesJC this isn't a priority for current development, but I'll slot it in.

**Comment by MattMilesJC** [comment] 2020-07-14 20:55
Thanks for the convo on this one, guys.  I agree with where we’re landing as per Lucas’ note below.  In addition to ‘not wanting them to leave easily’ it’s also just a matter of strange optics when you’re looking at a dashboard of events and groups that says “don’t attend, don’t attend, leave, leave, leave…” ahaha.   The homescreen is a place to remind people what they’re involved in and part of vs. reminding them that they can leave everything they’ve joined if you know what I mean.

Thanks guys!
Matt

Matt Miles

m: 647.746.0242
www.jesuscollective.com<http://www.jesuscollective.com/>
www.themeetinghouse.com<http://www.themeetinghouse.com/>

Hear what people are saying about Jesus Collective!<https://www.youtube.com/watch?v=TI1eg4GunV8>

**Comment by GeorgeBellTMH** [comment] 2020-07-17 04:01
Sounds good, we will change all of them to green dots for consistency.

**Comment by lucastbelem** [comment] 2021-04-29 19:50
Closing this for Nathan's review.

**Closed by lucastbelem** 2021-04-29 19:50 UTC
Labels: Secondary Priority
