### ISSUE TITLE
Series in resource re-ordering themselves

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#641] opened 2021-01-29 02:54 UTC
The resource re-ordered itself, which means that now when the user goes to an age group page and goes to the list carousel, the series are not in order.
I.e. Family should come before "Miracles"
<img width="1438" alt="Screen Shot 2021-01-28 at 9 49 27 PM" src="https://user-images.githubusercontent.com/48295718/106225280-d2953980-61b2-11eb-9029-57a097e18800.png">

**Comment by GeorgeBellTMH** [comment] 2021-01-30 09:46
Duplicate of #612/#611

**Closed by GeorgeBellTMH** 2021-01-30 09:46 UTC
