### ISSUE TITLE
Payment processing

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#374] opened 2020-07-24 18:57 UTC

**Comment by lucastbelem** [comment] 2020-07-27 18:04
Jesus Collective payment processing needs are two-fold:

First, a payment processing solution for purchases (i.e. partnerships, friendships, OLCs, curriculum). Requirements for this:
- An interface as per Jesus Collective design where users can process payment as they purchase one of Jesus Collective offerings;
- Donors must be able to process payment by credit card;
- Interface needs to connect with Moneris for processing the actual payment;
- Jesus Collective does not want to keep user credit card information;
- The ability to issue receipts as users purchase products;
- The ability to generate invoices that users can: a) be emailed; b) access via their profile on the platform;
- Remind customers that their memberships are coming up and issue renewal invoices for payments;

Essentially, Jesus Collective needs to store data on transaction details, process payments, and keep track of accounting. The suggestion came up today to use existing software that can handle the accounting side (i.e. Quickbooks Online) and Moneris for payment processing (although Quickbooks processes payments as well). Then, the platform itself is used as a front end spot for these things. The status of someone's membership needs to live in the platform also.

I'm sure there are lots of questions here. Hit me.

Second need: a donations system similar to what is being built for TMH. The difference however, is that JC donations would not connect to F1. Instead, we need to come up an in-house solution, or use a simpler version of F1. Thoughts?

**Comment by lucastbelem** [comment] 2020-07-27 18:19
Something that has come up in regards to using Quickbooks is whether it would generate automatic invoices for immediate transactions. I.e. partners can be invoiced and pay later. However, Friends will be able to sign up for a product and pay instantly. An invoice should be generated instantly as well. Question is: Can the platform handle this through quickbooks or we could consider opening a shopify account - this adds a third third-party to this process.

**Comment by lucastbelem** [comment] 2020-07-27 18:20
Moneris may actually be able to handle some of these e-commerce situations.

**Comment by JonEsparaz** [comment] 2020-07-27 18:28
I'd suggest trying to keep everything within a single payment platform since speedy development is key for Jesus Collective. Stripe is a good option if Moneris can't do it.

**Comment by lucastbelem** [comment] 2020-07-27 18:29
We can look into Stripe. The leaning towards of Moneris is simply due to the fact that we already have an account with them and use their services for some things. I can do a bit research into Stripe.

**Comment by lucastbelem** [comment] 2020-07-27 18:30
Do you recommend Stripe because of what you've seen of Moneris in terms of integration?

**Comment by JonEsparaz** [comment] 2020-07-27 18:36
Moneris can probably do it, I've just found their documentation a little unclear, so I'm not sure how easy the integrations will be.

I recommend Stripe because it is the payment platform I'm most familiar with, so I'm certain we can quickly add the integrations we're looking for.

**Comment by JonEsparaz** [comment] 2020-07-27 18:38
What I'm trying to say is, let's keep Stripe in mind in case Moneris doesn't work out.

**Comment by GeorgeBellTMH** [comment] 2020-07-27 18:41
I just looked at stripe. It’s night and day better than Moneris...

Sent from my iPhone

On Jul 27, 2020, at 2:38 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

What I'm trying to say is, let's keep Stripe in mind in case Moneris doesn't work out.

**Comment by JonEsparaz** [comment] 2020-07-27 18:45
Also, I inquired with Stripe a while ago for another project about non-profit pricing (not just if JC applies)... Here's what I was told:

- 2.2% + 30c for Visa / MC transactions made with Canadian credit cards
- 3.2% + 30c for Visa / MC transactions made with international credit cards (this will only be applied if any of your donors happen to use an international Visa or MC)
- 3.5% + 0c for American Express transactions

**Comment by GeorgeBellTMH** [comment] 2020-07-29 21:12
@lucastbelem let us know when you get the account setup.

**Comment by lucastbelem** [comment] 2020-07-30 19:34
@GeorgeBellTMH @JonEsparaz for Jesus Collective, I talked to Zulema today and got confirmation that we can move forward to set up payment through paypal for Leadership Development. This should make it pretty simple, I think. Let's chat more, but I'd love it if the following was possible:

- User applies via formstack as is
- JC admin needs to be able to send an approval email (off platform) which includes a link to their sign up flow
- Their sign up flow would include the payment screen as designed here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=1337%3A35855 (may need to modify and remove the non-paypal payment option)
- Payment is executed through paypal with the info entered on payment screen in-platform by user pre-populated in the paypal screen
- User is sent back to platform via the popup screen that says "payment processed successfully". 
- User proceeds to create profile and access to course via dashboard

**Comment by JonEsparaz** [comment] 2020-07-30 22:42
@lucastbelem for next week, can we get a PayPal account set up so George and I can test?

@GeorgeBellTMH I got the Javascript SDK to render the PayPal buttons in React Native (I needed to disable Typescript on the component though). We can explore the PayPal REST API if needed...

**Comment by GeorgeBellTMH** [comment] 2020-07-30 23:44
We already have one. I’ll find out the details and send tonite.

Sent from my iPhone

On Jul 30, 2020, at 6:43 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@lucastbelem<https://github.com/lucastbelem> for next week, can we get a PayPal account set up so George and I can test?

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> I got the Javascript SDK to render the PayPal buttons in React Native (I needed to disable Typescript on the component though). We can explore the PayPal REST API if needed...

**Comment by GeorgeBellTMH** [comment] 2020-08-02 21:37
Can we connect on this on Tuesday...I think we can set stuff up quicker if we do a zoom...

Lucas do you know how much it will be CAD$?

**Comment by lucastbelem** [comment] 2020-08-05 15:13
Hey team,

I talked to the JC team today and here's the flow that is planned for the pilot:

**New platform user**
- User applies via the marketing website
- JC team approves application offline and sends user email with link to sign up
- User signs up by creating their account
**- Account creation leads to payment screen (via paypal)
- Processed payment returns them to the platform with confirmation**
- User is prompted to create their profile
- JC team adds user to triad in course
- User gets access to course

**Existing platform user**
- User applies via marketing website OR via the marketing course page within the platform
**- JC team approves application offline and sends user email with link to payment screen (via paypal)
- Processed payment returns user to the platform with confirmation**
- JC team adds user to triad in course
- User gets access to course

**Comment by lucastbelem** [comment] 2020-08-07 13:09
Ayden is out.

**Comment by GeorgeBellTMH** [comment] 2020-09-24 06:51
- [X] Payment button added to course screen
- [X] Setup a course in the admin page (click the rocket and add a product)
- [X] The flow works and is currently set to use the PayPal Sandbox (you need to create sandbox users to test it)
- [X] On successful payment we save the data from PayPal and save to dynamo

There is some more stuff to do, but I'm going to put it on the main LD ticket...and close this ticket

**Closed by GeorgeBellTMH** 2020-09-24 06:51 UTC
