### ISSUE TITLE
Not all profile pins show on the map

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#327] opened 2020-07-14 13:45 UTC
**Describe the bug**
It doesn't look like everyone's profile pins show on the map? I can't find mine on the map.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment] 2020-07-14 14:12
Duplicate of #280 ...

**Closed by GeorgeBellTMH** 2020-07-14 14:12 UTC
