### ISSUE TITLE
Resources: explicit linking

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#205] opened 2020-06-17 17:50 UTC
Right now if I click on a specific resource, the URL doesn’t change, which makes bookmarking a series in your browser impossible.

**Comment by GeorgeBellTMH** [comment] 2020-06-23 07:16
Need to add routes in homepage/index.tsx similar to how groups is setup, but with more properties.

**Comment by GeorgeBellTMH** [comment] 2020-06-23 07:20
Duplicate of #132

**Closed** 2020-06-23 07:20 UTC
