### ISSUE TITLE
Start Conversation buttons -- boxes too wide + font size too big + font not centred vertically

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#356] opened 2020-07-21 12:31 UTC
The start conversation buttons (on the dashboard, and when you view other people's profile pages) are very wide -- should be less wide.  And the font size in the button seems too large relative to the name and role description font sizes.  See original figma design. 

Also start conversation text is not centred vertically in the buttons.

![image](https://user-images.githubusercontent.com/68029138/88055080-644d2b80-cb2c-11ea-822f-c077217dcb18.png)

![image](https://user-images.githubusercontent.com/68029138/88057135-9f049300-cb2f-11ea-8d69-9c8333591061.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucastbelem** [comment] 2020-07-21 18:15
Duplicate of #158

**Closed** 2020-09-24 02:55 UTC
Labels: V2
